<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../WinFormsApp1/SystemCleaner.cs" Link="SystemCleaner.cs" />
    <Compile Include="../WinFormsApp1/WorkspaceStore.cs" Link="WorkspaceStore.cs" />
    <Compile Include="../WinFormsApp1/CommandExecutor.cs" Link="CommandExecutor.cs" />
  </ItemGroup>
</Project>
